# Generated by Django 3.1.3 on 2020-12-14 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_profile_last_update_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bannerImage',
            new_name='banner_image',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profileImage',
            new_name='profile_image',
        ),
    ]
