# Generated by Django 3.1.3 on 2020-12-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201212_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_update_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
